### ISSUE TITLE
Ask for codes

### ISSUE THREAD

**Issue by kk17860** [Ruixxxx/LSSANet#1]
Thanks for your wonderful work in pulmonary nodule detection. Would you like to release the full code?

**Comment by Ruixxxx** [comment]
Thanks for your attention! We just released the code.

**Comment by Ruixxxx** [comment]
> Thanks for your wonderful work in pulmonary nodule detection. Would you like to release the full code?



> Thanks for your wonderful work in pulmonary nodule detection. Would you like to release the full code?

Thanks for your attention! We just released the code.

**Comment by Ruixxxx** [comment]
Thanks for your attention! We just released the code.

**Comment by kk17860** [comment]
Thanks for the reply.
