### ISSUE TITLE
How long does it take to train ?

### ISSUE THREAD

**Issue by cvbird** [Ruixxxx/LSSANet#2]
Hi authors, thank you for your project. I wonder how long does it take to train on the PN9 and luna16 dataset respectively ? 
As mentioned in your paper, 3 NVIDIA GeForce RTX 3090 GPU with 24GB memory were used.

**Comment by Ruixxxx** [comment]
> Hi authors, thank you for your project. I wonder how long does it take to train on the PN9 and luna16 dataset respectively ? As mentioned in your paper, 3 NVIDIA GeForce RTX 3090 GPU with 24GB memory were used.

Thanks for asking! In our implementation, it takes around 3.5h per epoch for training the PN9 using our LSSANet, and around 1.5h using our LSSANet without FPR. As for the LUNA16, we didn't perform experiments on it. The training time per epoch may be reduced to 1/10 of the PN9's, but note that the model may need more training epochs and there is no pre-trained model provided.

**Comment by Ruixxxx** [comment]
> Hi authors, thank you for your project. I wonder how long does it take to train on the PN9 and luna16 dataset respectively ? As mentioned in your paper, 3 NVIDIA GeForce RTX 3090 GPU with 24GB memory were used.

Thanks for asking! In our implementation, it takes around 3.5h per epoch for training the PN9 using our LSSANet, and around 1.5h using our LSSANet without FPR. As for the LUNA16, we didn't perform experiments on it. The training time per epoch may be reduced to 1/10 of the PN9's, but please note that the model may need more training epochs and there is no pre-trained model provided.

**Comment by cvbird** [comment]
> > Hi authors, thank you for your project. I wonder how long does it take to train on the PN9 and luna16 dataset respectively ? As mentioned in your paper, 3 NVIDIA GeForce RTX 3090 GPU with 24GB memory were used.
> 
> Thanks for asking! In our implementation, it takes around 3.5h per epoch for training the PN9 using our LSSANet, and around 1.5h using our LSSANet without FPR. As for the LUNA16, we didn't perform experiments on it. The training time per epoch may be reduced to 1/10 of the PN9's, but note that the model may need more training epochs and there is no pre-trained model provided.

Thank you for your quick reply. One more question about the training epochs. I check your paper and can not find this setting. I wonder whether you run 200 epoch as SANet ?  
Besides, I also checked your configuration file and see that your setting is 200 (400 is annotated). I wonder whether your had trained with 400 epochs. If so, how about the performance ?

Best,
cvbird

**Comment by Ruixxxx** [comment]
> > > Hi authors, thank you for your project. I wonder how long does it take to train on the PN9 and luna16 dataset respectively ? As mentioned in your paper, 3 NVIDIA GeForce RTX 3090 GPU with 24GB memory were used.
> > 
> > 
> > Thanks for asking! In our implementation, it takes around 3.5h per epoch for training the PN9 using our LSSANet, and around 1.5h using our LSSANet without FPR. As for the LUNA16, we didn't perform experiments on it. The training time per epoch may be reduced to 1/10 of the PN9's, but note that the model may need more training epochs and there is no pre-trained model provided.
> 
> Thank you for your quick reply. One more question about the training epochs. I check your paper and can not find this setting. I wonder whether you run 200 epoch as SANet ? Besides, I also checked your configuration file and see that your setting is 200 (400 is annotated). I wonder whether your had trained with 400 epochs. If so, how about the performance ?
> 
> Best, cvbird

Thanks for your interest! More information can be find in the .ckpt we provided.

**Comment by cvbird** [comment]
> > > > Hi authors, thank you for your project. I wonder how long does it take to train on the PN9 and luna16 dataset respectively ? As mentioned in your paper, 3 NVIDIA GeForce RTX 3090 GPU with 24GB memory were used.
> > > 
> > > 
> > > Thanks for asking! In our implementation, it takes around 3.5h per epoch for training the PN9 using our LSSANet, and around 1.5h using our LSSANet without FPR. As for the LUNA16, we didn't perform experiments on it. The training time per epoch may be reduced to 1/10 of the PN9's, but note that the model may need more training epochs and there is no pre-trained model provided.
> > 
> > 
> > Thank you for your quick reply. One more question about the training epochs. I check your paper and can not find this setting. I wonder whether you run 200 epoch as SANet ? Besides, I also checked your configuration file and see that your setting is 200 (400 is annotated). I wonder whether your had trained with 400 epochs. If so, how about the performance ?
> > Best, cvbird
> 
> Thanks for your interest! More information can be find in the .ckpt we provided.

Got it and thank you again.
