### ISSUE TITLE
batch_size

### ISSUE THREAD

**Issue by kk17860** [Ruixxxx/LSSANet#3]
Thanks for your wonderful work in pulmonary nodule detection. Why is batch_size equal to 1 in single_test.py? It takes a lot of time to test. Can I set batch_size equal to 2?

**Comment by Ruixxxx** [comment]
> Thanks for your wonderful work in pulmonary nodule detection. Why is batch_size equal to 1 in single_test.py? It takes a lot of time to test. Can I set batch_size equal to 2?

Thanks for your interest! Since the test CT images are not cropped to 128x128x128 and the single_test.py does not support multi-gpu test, the batch_size is set to 1. You may set the batch_size to 2 if you have enough GPU memory.

**Comment by kk17860** [comment]
Thanks for your reply.
