### ISSUE TITLE
About FPR module

### ISSUE THREAD

**Issue by cvbird** [Ruixxxx/LSSANet#4]
#2 
Following my question in the above issue, I have some other questions.
Firstly. I read the code and compared it with SANet. From my understanding, the variable "use_rcnn" in SANet_L3S2 controls the use of FPR. This variable is set to be True when the training epoch is larger than 10 and is always set to be True when evaluation.  Is my understanding correct ?

Secondly, since my gpu is not so powerful, now I had only trained it for 75 epochs and the evaluation results are:

fps:  0.125 , sensitivity:  0.30703624733475476
fps:  0.25 , sensitivity:  0.4004264392324094
fps:  0.5 , sensitivity:  0.5170575692963753
fps:  1 , sensitivity:  0.6328358208955224
fps:  2 , sensitivity:  0.7339019189765459
fps:  4 , sensitivity:  0.8155650319829424
fps:  8 , sensitivity:  0.873773987206823
=============================================
average FROC:  0.6115138592750533

The performance is far from the reported values in the paper. I wonder whether this is normal? Did you trained the mode from scratch or using the pretrained model from SANet to initialize the LSSANet ?

Thank you and looking forward to your reply.
Best,
cvbird

**Comment by Ruixxxx** [comment]
> 

Hi cvbird,

On your first question, your understanding is totally correct.
On your second question, we actually initialize the LSSANet using the pretrained model provided in SANet.

Thanks for your interest!
Best,
Rui

**Comment by cvbird** [comment]
> > 
> 
> Hi cvbird,
> 
> On your first question, your understanding is totally correct. On your second question, we actually initialize the LSSANet using the pretrained model provided in SANet.
> 
> Thanks for your interest! Best, Rui

Thank you very much.
