### ISSUE TITLE
PN9

### ISSUE THREAD

**Issue by thestars-maker** [Ruixxxx/LSSANet#6]
How can the PN9 dataset be processed into a 2D data format such as VOC or COCO, thanks a lot for sharing!

**Comment by Ruixxxx** [comment]
> How can the PN9 dataset be processed into a 2D data format such as VOC or COCO, thanks a lot for sharing!

Hi,

Thanks for your attention! A simple way to convert the PN9 dataset into a 2D data format is by extracting slices from the 3D volume along the z, y, or x-axis.

**Comment by thestars-maker** [comment]
Thank you for your reply, do we usually take the Z-axis as the slice to extract the 2D information or can any of the axes be used?

**Comment by Ruixxxx** [comment]
> Thank you for your reply, do we usually take the Z-axis as the slice to extract the 2D information or can any of the axes be used?

You can extract 2D slices from any of the three axes. Extracting 2D slices along the Z-axis is the most common choice in CT imaging. The choice of which axis to use depends on the specific requirements of the analysis or visualization you are performing.

**Comment by thestars-maker** [comment]
I'm very sorry, I noticed that the author himself open-sources the data i.e. in png or .npy format, do I need to convert it to 3D data now, and how is this accomplished?

**Comment by Ruixxxx** [comment]
> I'm very sorry, I noticed that the author himself open-sources the data i.e. in png or .npy format, do I need to convert it to 3D data now, and how is this accomplished?

Yes, you need to convert the open-source data into 3D data, thus running the 3D models. For example, you can write a Python file to load and convert the .jpg files in one folder, which represents one CT image, into one 3D matrix.
